name: test
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: "JOB1"
    steps:
      - name: "example output"
        id: "my_step"
        run: |
          my_var="Hello world"
          echo "Output [$my_var]"
          echo "my_var=$my_var" >> $GITHUB_OUTPUT

      - name: "example receive"
        run: |
          echo "Output [${{steps.my_step.outputs.my_var}}]"
